/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package br.gb.tech

class LibraryTest {
//    @Test fun someLibraryMethodReturnsTrue() {
//        val classUnderTest = Library()
//        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
//    }
}
